name: nmx-live-datareduction

services:
  monitor-data:
    image: python:3.12
    container_name: monitor-data
    volumes:
      - ./beamlime:/app
    working_dir: /app
    environment:
      BEAMLIME_ENV: docker
      BEAMLIME_INSTRUMENT: ${BEAMLIME_INSTRUMENT:-dummy}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-SCRAM-SHA-256}
      KAFKA_SASL_USERNAME: ${KAFKA_SASL_USERNAME:-DUMMY}
      KAFKA_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD:-DUMMY}
      KAFKA2_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
      KAFKA2_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}
      KAFKA2_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-SCRAM-SHA-256}
      KAFKA2_SASL_USERNAME: ${KAFKA_SASL_USERNAME:-DUMMY}
      KAFKA2_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD:-DUMMY}
    command: sh -c "python -m pip install -e . && python -m beamlime.services.monitor_data --instrument nmx"

  detector-data:
    image: python:3.12
    container_name: detector-data
    volumes:
      - ./beamlime:/app
    working_dir: /app
    environment:
      BEAMLIME_ENV: docker
      BEAMLIME_INSTRUMENT: ${BEAMLIME_INSTRUMENT:-nmx}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-SCRAM-SHA-256}
      KAFKA_SASL_USERNAME: ${KAFKA_SASL_USERNAME:-DUMMY}
      KAFKA_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD:-DUMMY}
      KAFKA2_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
      KAFKA2_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}
      KAFKA2_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-SCRAM-SHA-256}
      KAFKA2_SASL_USERNAME: ${KAFKA_SASL_USERNAME:-DUMMY}
      KAFKA2_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD:-DUMMY}
    command: sh -c "python -m pip install -e . && python -m beamlime.services.detector_data --instrument nmx"

  dashboard:
    image: python:3.12
    container_name: dashboard
    volumes:
      - ./beamlime:/app
    working_dir: /app
    ports:
      - "4000:4000"
    environment:
      BEAMLIME_ENV: docker
      BEAMLIME_INSTRUMENT: ${BEAMLIME_INSTRUMENT:-nmx}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-SCRAM-SHA-256}
      KAFKA_SASL_USERNAME: ${KAFKA_SASL_USERNAME:-DUMMY}
      KAFKA_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD:-DUMMY}
      KAFKA2_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
      KAFKA2_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}
      KAFKA2_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-SCRAM-SHA-256}
      KAFKA2_SASL_USERNAME: ${KAFKA_SASL_USERNAME:-DUMMY}
      KAFKA2_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD:-DUMMY}
    command: sh -c "python -m pip install -e .[dashboard] && gunicorn beamlime.services.wsgi:application -b 0.0.0.0:4000"
